server:
  port: ${PORT:5000}
spring:
  security:
    user:
       password: ${EUREKA_USER_PASSWORD:password}

eureka:
  instance:
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:${server.port}}/eureka/
     